name: xfstests

on:
  push:
    branches:
      - '**'
    paths:
      - 'generic/stress.py'
      - 'generic/stress.py.data/ci.yaml'
      - '.github/workflows/stress-ng*'
  pull_request:
    branches:
      - '**'
    paths:
      - 'generic/stress.py'
      - 'generic/stress.py.data/ci.yaml'
      - '.github/workflows/stress-ng*'
  workflow_dispatch: # manual trigger

# required for publishing Junit results
permissions:
  contents: read
  checks: write
  id-token: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Run all fs ci.yaml config
        config:
          - generic/stress-ng.py.data/ci.yaml
        container:
          - ubuntu:latest
          - fedora:latest # Add images for CentOS, RHEL, SLES, etc. here

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Create directories for the results
        run: mkdir -p avocado-results

        # We need docker to run in privileged with bind mounted volumes
      - name: Docker Run
        run: |
            docker run --privileged -d --name avocado_test_container \
                        -v ${{ github.workspace }}:/workspace \
                        -v $PWD/avocado-results:/root/avocado/job-results \
                        ${{ matrix.container }} sleep infinity

        # Install dependencies inside the container
      - name: Install dependencies
        run: |
          docker exec avocado_test_container bash -c "\
          if [[ '${{ matrix.container }}' == 'ubuntu:latest' ]]; then \
            apt-get update && apt-get -y upgrade && apt-get install -y build-essential python3 python3-pip; \
          elif [[ '${{ matrix.container }}' == 'fedora:latest' ]]; then \
            dnf -y update && dnf -y groupinstall 'Development Tools' && dnf -y install python3 python3-pip hostname which; \
          fi && \
          pip3 install avocado-framework && \
          pip3 install avocado-framework-plugin-varianter-yaml-to-mux \
          "

      - name: Run xfstests.py with Avocado
        run: |
          docker exec avocado_test_container bash -c "cd /workspace && avocado --show test run generic/stress-ng.py --max-parallel-tasks 1 -m ${{ matrix.config }}"

        # It seems upload name cannot have '/'
      - name: Prepare artifact name
        id: prepare
        run: |
          ARTIFACT_NAME=$(echo "${{ matrix.config }}" | tr '/' '_')
          echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: "xfstests_${{ env.ARTIFACT_NAME }}"
          path: ./avocado-results/

      - name: "Publish results"
        continue-on-error: true
        uses: mikepenz/action-junit-report@v3
        with:
          commit: ${{ github.sha }}
          detailed_summary: true
          annotate_notice: true
          include_passed: true
          report_paths: './avocado-results/**/*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
