name: xfstests

on:
  push:
    branches:
      - '**'
    paths:
      - 'fs/xfstests.py'
      - '.github/workflows/xfstests*'
  pull_request:
    branches:
      - '**'
    paths:
      - 'fs/xfstests.py'
      - '.github/workflows/xfstests*'
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  id-token: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - fs/xfstests.py.data/ext2/test.yaml
          - fs/xfstests.py.data/ext4/test.yaml
          - fs/xfstests.py.data/xfs/test.yaml
          - fs/xfstests.py.data/btrfs/test.yaml
        container:
          - ubuntu:latest
          - fedora:latest
          # Add images for CentOS, RHEL, SLES, etc. here

    container:
      image: ${{ matrix.container }}

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y upgrade
        sudo apt-get install build-essential
        pip3 install avocado-framework
        pip3 install avocado-framework-plugin-varianter-yaml-to-mux
        AVOCADO_PATH=$(dirname $(which avocado))
        echo "$AVOCADO_PATH" >> $GITHUB_PATH
        # Include any other dependencies your tests might need

    - name: Run xfstests.py with Avocado
      run: |
        sudo env "PATH=$PATH" avocado --show test run fs/xfstests.py --max-parallel-tasks 1 -m ${{ matrix.config }}

    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: "xfstests_${{matrix.config}}"
        path: /root/avocado/job-results/

    - name: "Publish results"
      continue-on-error: true
      uses: mikepenz/action-junit-report@v3
      with:
        commit: ${{ github.sha }}
        detailed_summary: true
        annotate_notice: true
        include_passed: true
        report_paths: '/root/avocado/job-results/**/*.xml'
        github_token: ${{ secrets.GITHUB_TOKEN }}
